'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=(n,d=4)=>Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
let openSteps=new Set(['01']);
let floors=[{h:4,w:500},{h:8,w:500},{h:12,w:500},{h:16,w:450}],faults=[],current=null,params=null;
const opts=arr=>arr.map((x,i)=>`<option value="${i}">${esc(x)}</option>`).join('');
$('directionInputs').innerHTML=['x','y'].map(a=>`<h3>${a.toUpperCase()} 向</h3><label>經驗週期類別<select id="ct${a}"><option value="0.07">RC／SRC 剛構架、鋼偏心斜撐 · 0.070</option><option value="0.085">鋼剛構架（無剛性牆／加勁）· 0.085</option><option value="0.05">其他／含剪力牆或加勁 · 0.050</option></select></label><div class="grid2"><label>分析週期 T${a}（s）<input id="t${a}" type="number" value="0.56" min="0.001" step="0.01"></label><label>韌性容量 R${a}<input id="r${a}" type="number" value="4" min="1" max="5" step="0.1"></label></div>`).join('')+'<p class="hint">R 預設 4 為示範；須由表 1-3 依實際結構系統選定。經驗週期係數與 R 分別確認。</p>';
function floorUI(){ $('floorInputs').innerHTML=floors.map((f,i)=>`<tr><td>${i+1}F${i===floors.length-1?' / 屋頂':''}</td><td><input aria-label="${i+1}樓標高" data-floor="${i}" data-key="h" type="number" min="0.01" step="0.1" value="${f.h}"></td><td><input aria-label="${i+1}樓重量" data-floor="${i}" data-key="w" type="number" min="0.01" step="10" value="${f.w}"></td><td><button data-remove-floor="${i}" ${floors.length===1?'disabled':''}>移除</button></td></tr>`).join('');}
function faultUI(){ $('faultRows').innerHTML=faults.map((f,i)=>`<div class="fault"><label>斷層／表列行政區組別<select data-fault="${i}" data-key="index">${DATA.faults.map((d,j)=>`<option value="${j}" ${j===f.index?'selected':''}>${esc(d.name)} · 第 ${j+1} 組</option>`).join('')}</select></label><p class="hint">${esc(DATA.faults[f.index].area)}</p><label>最短水平距離（km）<input data-fault="${i}" data-key="distance" type="number" min="0" step="0.1" value="${f.distance}"></label><button data-remove-fault="${i}">移除此斷層</button></div>`).join('');}
const locations=[...DATA.general.map(r=>({city:r[0],district:r[1],village:r[2]||'全區／表列範圍',raw:r.slice(3,7),near:r[7],mode:r[7]?'near':'general'})),...DATA.basin.map(r=>({city:r[0],district:r[1],village:r[2],zone:r[6],mode:'basin'}))];
function choices(id,items){$(id).innerHTML=items.map(x=>`<option>${esc(x)}</option>`).join('');}
function eligibleLocations(){const mode=$('mode').value;return locations.filter(l=>l.mode===mode&&(mode!=='general'||l.city!=='臺北市')&&(mode!=='basin'||['臺北市','新北市'].includes(l.city)));}
function refreshLocations(){const previous=$('city').value,available=[...new Set(eligibleLocations().map(l=>l.city))];choices('city',available);if(available.includes(previous))$('city').value=previous;else if($('mode').value==='basin'&&available.includes('臺北市'))$('city').value='臺北市';cityChange();}
function cityChange(){const previous=$('district').value,available=[...new Set(eligibleLocations().filter(l=>l.city===$('city').value).map(l=>l.district))];choices('district',available);if(available.includes(previous))$('district').value=previous;districtChange();}
function districtChange(){const previous=$('village').value,rows=eligibleLocations().filter(l=>l.city===$('city').value&&l.district===$('district').value);$('village').innerHTML=rows.map(r=>`<option value="${locations.indexOf(r)}">${esc(r.village)} · ${r.mode==='basin'?'盆地':r.mode==='near'?'近斷層':'一般'}</option>`).join('');if(rows.some(r=>String(locations.indexOf(r))===previous))$('village').value=previous;$('applyLocation').disabled=!rows.length;}
refreshLocations();if([...$('city').options].some(o=>o.value==='桃園市'))$('city').value='桃園市';cityChange();
$('city').addEventListener('change',cityChange);$('district').addEventListener('change',districtChange);
$('applyLocation').onclick=()=>{let r=locations[Number($('village').value)];if(!r||!eligibleLocations().includes(r)||$('village').value==='')return;if(r.mode==='basin')$('zone').value=r.zone;else r.raw.forEach((v,i)=>$('s'+i).value=v);$('locationNote').textContent=[r.city,r.district,r.village].join(' ')+(r.near?'｜鄰近：'+r.near+'；請加入所有適用斷層並量測距離。':'')+(r.city==='臺北市'||r.city==='新北市'?'｜113 年修正表':'｜附件震區表');modeUI();update();};
function modeUI(){let mode=$('mode').value;$('generalInputs').hidden=mode==='basin';$('basinInputs').hidden=mode!=='basin';$('nearInputs').hidden=mode!=='near';}
$('mode').addEventListener('change',()=>{$('locationNote').textContent='已手動切換工址類型，請重新確認基地與參數。';refreshLocations();modeUI();});
function read(){const n=id=>$(id).value.trim()===''?NaN:Number($(id).value);return {mode:$('mode').value,fumBasis:$('fumBasis').value,zone:n('zone'),soil:n('soil'),raw:[0,1,2,3].map(i=>n('s'+i)),height:n('height'),I:n('I'),ay:n('ay'),tx:n('tx'),ty:n('ty'),ctx:n('ctx'),cty:n('cty'),rx:n('rx'),ry:n('ry'),tv:n('tv'),rv:n('rv'),depth:n('depth'),bw:n('bw'),floors,irregular:$('irregular').value,mixed:$('mixed').value,special:$('special').value};}
const table=(heads,rows)=>`<div class="tablewrap"><table><thead><tr>${heads.map(s=>`<th>${s}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
function metric(label,d){return `<div class="metric"><div class="eyebrow">${label}</div><strong>${fmt(d.V,2)}<small>tf</small></strong><p class="coef">C = V/W = ${fmt(d.C)}</p><p>${d.control}<br>T = ${fmt(d.t,3)} s</p></div>`;}
function update(){document.querySelectorAll('#steps details').forEach(el=>{if(el.open)openSteps.add(el.dataset.step);else openSteps.delete(el.dataset.step);});try{let p=read();if(!Number.isFinite(p.depth)||p.depth<0||!Number.isFinite(p.bw)||p.bw<=0)throw Error('地下室深度須 ≥0，該層重量須 >0。');if(p.rv>3)throw Error('本工具垂直韌性 Rv 限 1–3；其他取值須專案評估。');if(p.rx>5||p.ry>5)throw Error('R 超出本工具支援範圍 1–5，請確認表 1-3。');const r=Engine.calculate(p,faults.map(f=>({...DATA.faults[f.index],distance:f.distance})));params=p;current=r;$('calcState').textContent='已更新';$('calcState').className='ready';
$('status').className='status'+(r.dynamic?' warn':'');$('status').textContent=r.dynamic?'須另作動力／專案分析｜下列為地震力需求與靜力基準，不能以本頁取代 §3.1 動力分析。':'靜力法初步篩選：高度與樓層數未達動力門檻。仍須確認結構系統、規則性與地盤條件。';
$('results').innerHTML='<div class="metrics">'+metric('X 向設計總橫力',r.x)+metric('Y 向設計總橫力',r.y)+`<div class="metric"><div class="eyebrow">地上總重量 W</div><strong>${fmt(r.W,0)}<small>tf</small></strong><p class="coef">${p.floors.length} 層 · Hn ${fmt(p.height,1)} m</p><p>X：${fmt(r.x.V*9.80665,1)} kN<br>Y：${fmt(r.y.V*9.80665,1)} kN</p></div></div>`;
$('siteTable').innerHTML=table(['工址參數','SDS','SD1','SMS','SM1'],[['放大係數 Fa / Fv',...r.site.factors.map(n=>fmt(n,3))],['工址譜係數',...r.site.values.map(n=>fmt(n,4))]])+`<p class="hint">T₀D = SD1 / SDS = ${fmt(r.t0)} s　｜　T₀M = SM1 / SMS = ${fmt(r.tm)} s</p>`;
renderChart();renderFloors();renderSteps();$('print').disabled=false;document.dispatchEvent(new Event('seismic-updated'));
}catch(e){current=null;params=null;$('calcState').textContent='待修正';$('calcState').className='invalid';$('status').className='status error';$('status').textContent=e.message;$('results').innerHTML='<div class="note">參數尚未完整，暫停顯示計算結果。修正後將自動重新計算。</div>';['chart','siteTable','floorResults','steps'].forEach(id=>$(id).innerHTML='');$('print').disabled=true;document.dispatchEvent(new Event('seismic-updated'));}}
function renderChart(){if(!current)return;const r=current,limit=Math.max(4,Math.ceil(Math.max(r.t0,r.tm)*2.8),Math.ceil(Math.max(r.x.t,r.y.t))),maxY=Math.max(r.s,r.m)*1.15,staticMode=$('chartType').value==='static',x=t=>56+t/limit*690,y=v=>285-v/maxY*235;let svg='<svg viewBox="0 0 790 330" role="img" aria-label="設計地震與最大考量地震反應譜"><rect x="56" y="35" width="690" height="250" fill="#fafcfe"/>';
for(let i=0;i<=5;i++){let v=maxY*i/5;svg+=`<line x1="56" x2="746" y1="${y(v)}" y2="${y(v)}" stroke="#e2eaf2"/><text x="45" y="${y(v)+4}" text-anchor="end" font-size="12" fill="#70849a">${fmt(v,2)}</text>`;}
for(let i=0;i<=limit;i++){svg+=`<text x="${x(i)}" y="308" text-anchor="middle" font-size="12" fill="#70849a">${i}</text>`;}
svg+='<text x="56" y="20" fill="#536d84" font-size="13">Sa（g/g）</text><text x="746" y="328" text-anchor="end" fill="#536d84" font-size="13">週期 T（s）</text>';
[[r.s,r.s1,'#2678c5'],[r.m,r.m1,'#169993']].forEach(([s,s1,c])=>{const ts=[...new Set([...Array.from({length:301},(_,i)=>i*limit/300),.2*s1/s,s1/s,2.5*s1/s])].filter(t=>t<=limit).sort((a,b)=>a-b);let path=ts.map((t,i)=>`${i?'L':'M'}${x(t).toFixed(2)},${y(Engine.spectrum(t,s,s1,staticMode)).toFixed(2)}`).join(' ');svg+=`<path d="${path}" fill="none" stroke="${c}" stroke-width="3"/>`;});
[r.x,r.y].forEach((d,i)=>{svg+=`<line x1="${x(d.t)}" x2="${x(d.t)}" y1="35" y2="285" stroke="${i?'#5f7b87':'#132942'}" stroke-dasharray="5 5"/><text x="${x(d.t)+7}" y="${48+i*18}" font-size="12" fill="#18324a">${i?'Y':'X'} ${fmt(d.t,3)}s</text>`;});$('chart').innerHTML=svg+'</svg>';}
function renderFloors(){const r=current;let rows=r.dx.rows.map((f,i)=>[`${i+1}F`,fmt(f.force,2),fmt(r.dy.rows[i].force,2),fmt(f.shear,2),fmt(r.dy.rows[i].shear,2)]);$('floorResults').innerHTML=`<h3>豎向分配結果</h3><p class="hint">Fᵢ = (V − Ft) Wᵢhᵢ / ΣWⱼhⱼ；屋頂再加 Ft。T ≤0.7 s 時，本工具取 Ft = 0。</p>`+table(['樓層','Fx（tf）','Fy（tf）','Qx（tf）','Qy（tf）'],rows)+`<div class="note">ΣFx = ${fmt(r.dx.sumForce,3)} tf　／　ΣFy = ${fmt(r.dy.sumForce,3)} tf<br>頂層集中力 Ftx = ${fmt(r.dx.ft,3)} tf、Fty = ${fmt(r.dy.ft,3)} tf<br>基面力矩 ΣFh（未折減、含 Ft）：X ${fmt(r.dx.moment,2)}、Y ${fmt(r.dy.moment,2)} tf·m</div>`;}
function renderSteps(){let r=current,p=params;const step=(n,title,html)=>`<details class="step" ${openSteps.has(n)?'open':''} data-step="${n}"><summary><span>${n}</span> ${title}</summary><div class="step-content">${html}</div></details>`;let h=step('01','輸入摘要',`<p>${esc($('locationNote').textContent)}<br>工址：${esc($('mode').selectedOptions[0].text)}；FuM 依據：${p.fumBasis==='source'?'附件 T₀M':'規範式 (2-12) T₀D'}；I=${p.I}；αy=${p.ay}；Hn=${p.height} m；W=${fmt(r.W,2)} tf。</p>`);
if(r.nearRows.length)h+=step('02','近斷層查表內插',table(['斷層','km','Sˢᴰ','S¹ᴰ','Sˢᴹ','S¹ᴹ'],r.nearRows.map(f=>[esc(f.name),fmt(f.distance,2),...f.computed.map(n=>fmt(n))]))+'<p>各震區參數分別取最大值（含一般區域係數下限），再依地盤求 Fa、Fv。</p>');
h+=step('03','工址放大與轉換週期 · §2.5–2.7',`<div class="formula">SDS = Fa × Sˢᴰ = ${fmt(r.s)}<br>SD1 = Fv × S¹ᴰ = ${fmt(r.s1)}<br>SMS = Fa × Sˢᴹ = ${fmt(r.m)}<br>SM1 = Fv × S¹ᴹ = ${fmt(r.m1)}<br>T₀D = ${fmt(r.t0)} s；T₀M = ${fmt(r.tm)} s</div><p>臺北盆地直接採表 2-6(c)。其餘依表 2-4 線性內插。</p>`);
h+=step('04','週期限制與韌性折減 · §2.6、2.9',`<div class="formula">Tc = Ct × Hn^0.75；T = min(T分析, 1.4Tc)<br>Ra = 1 + (R − 1) / ${p.mode==='basin'?'2.0':'1.5'}<br>q = √(2Ra − 1)<br>Fu：T ≤ 0.2T₀ → 1 + (q−1)T/(0.2T₀)<br>0.2T₀ &lt; T ≤ 0.6T₀ → q<br>0.6T₀ &lt; T ≤ T₀ → q + (Ra−q)(T−0.6T₀)/(0.4T₀)<br>T &gt; T₀ → Ra</div>`+table(['項目','X 向','Y 向'],[['Ct',p.ctx,p.cty],['分析週期（s）',fmt(p.tx),fmt(p.ty)],['Tc（s）',fmt(r.x.Tc),fmt(r.y.Tc)],['1.4Tc（s）',fmt(1.4*r.x.Tc),fmt(1.4*r.y.Tc)],['採用 T（s）',fmt(r.x.t),fmt(r.y.t)],['R',p.rx,p.ry],['Ra',fmt(r.x.ra),fmt(r.y.ra)],['Fu',fmt(r.x.fd),fmt(r.y.fd)],[p.fumBasis==='source'?'FuM（附件 T₀M）':'FuM（式 2-12 T₀D）',fmt(r.x.fm),fmt(r.y.fm)]]));
h+=step('05','反應譜與修正',`<div class="formula">Sa(T) = S × (0.4 + 3T/T₀)，T ≤0.2T₀<br>= S，0.2T₀ &lt; T ≤T₀<br>= S₁/T，T₀ &lt; T ≤2.5T₀<br>= 0.4S，T &gt;2.5T₀（靜力下限）<br>q = Sa/F；m(q) = q（q≤0.3）；0.52q+0.144（0.3&lt;q&lt;0.8）；0.7q（q≥0.8）</div>`+table(['項目','X 向','Y 向'],[['SaD',fmt(r.x.sd),fmt(r.y.sd)],['SaM',fmt(r.x.sm),fmt(r.y.sm)],['(SaD/Fu)m',fmt(r.x.md),fmt(r.y.md)],['(SaM/FuM)m',fmt(r.x.mm),fmt(r.y.mm)]]));
h+=step('06','三種地震水準取控制值 · §2.2、2.10',`<div class="formula">Cd = I × (SaD/Fu)m / (1.4αy)<br>C* = I × Fu* × (SaD*/Fu*)m / (${r.div}αy)<br>CM = I × (SaM/FuM)m / (1.4αy)<br>C = max(Cd, C*, CM)；V = C × W</div><p>*：近斷層的中小度地震採一般區域係數另算譜與 Fu。以下先列無因次係數，再列力。</p>`+table(['地震水準','X 係數','X（tf）','Y 係數','Y（tf）'],[['設計 Vd',fmt(r.x.cd),fmt(r.x.cd*r.W,2),fmt(r.y.cd),fmt(r.y.cd*r.W,2)],['中小度 V*',fmt(r.x.cs),fmt(r.x.cs*r.W,2),fmt(r.y.cs),fmt(r.y.cs*r.W,2)],['最大考量 VM',fmt(r.x.cm),fmt(r.x.cm*r.W,2),fmt(r.y.cm),fmt(r.y.cm*r.W,2)],['控制 V',fmt(r.x.C),fmt(r.x.V,2),fmt(r.y.C),fmt(r.y.V,2)]]));
h+=step('07','垂直地震力 · §2.18',`<p>垂直譜採水平譜的 ${p.mode==='near'?'2/3':'1/2'}；Tv=${p.tv} s，Rv=${p.rv}。垂直 m(q) 分界採 ${p.mode==='near'?'0.2、0.53；中段加 0.096':'0.15、0.4；中段加 0.072'}。</p>`+table(['項目','計算值'],[['SaD,v / SaM,v',`${fmt(r.z.sd)} / ${fmt(r.z.sm)}`],['Fu,v / FuM,v',`${fmt(r.z.fd)} / ${fmt(r.z.fm)}`],['Cd,z / C*,z / CM,z',`${fmt(r.z.cd)} / ${fmt(r.z.cs)} / ${fmt(r.z.cm)}`],['樓板與梁 Kz',fmt(r.z.C)],['柱牆自重垂直係數',fmt(r.columnC)]])+`<div class="formula">樓板與梁：垂直地震載重 = ±${fmt(r.z.C)} × 對應靜載重<br>柱牆：±0.4 × ${p.mode==='near'?'(2/3)':'(1/2)'} × SDS × I / αy × 對應自重</div><p>各係數分別施加於其對應構件重量，勿將全部 W 重複施加。</p>`);
h+=step('08','層間位移用地震力 · §2.16.1',`<div class="formula">VD/W = Fu × (SaD/Fu)m / 4.2（I=1）<br>X：${fmt(r.x.driftC)} → ${fmt(r.x.driftV,2)} tf<br>Y：${fmt(r.y.driftC)} → ${fmt(r.y.driftV,2)} tf<br>VD/V：X ${fmt(r.x.driftC/r.x.C)}；Y ${fmt(r.y.driftC/r.y.C)}</div><p>以分析週期計算，不受 1.4Tc 與 0.4SDS 下限限制。此處只算施加地震力；實際層間位移角尚須結構分析，通常限值 0.005。</p>`);
const baseK=.1*Math.max(1-p.depth/40,.5)*p.I,kd=baseK*r.s,ks=kd/r.div,km=baseK*r.m;
h+=step('09','地下室各地震工況 · §2.12',`<div class="formula">KD = 0.1 × max(1−H/40, 0.5) × SDS × I<br>= 0.1 × ${fmt(Math.max(1-p.depth/40,.5))} × ${fmt(r.s)} × ${p.I} = ${fmt(kd)}<br>K* = KD / ${r.div} = ${fmt(ks)}<br>KM = 0.1 × max(1−H/40, 0.5) × SMS × I = ${fmt(km)}</div>`+table(['工況','K','該層水平力（tf）'],[['設計地震',fmt(kd),fmt(kd*p.bw,2)],['中小度地震',fmt(ks),fmt(ks*p.bw,2)],['最大考量地震',fmt(km),fmt(km*p.bw,2)]])+`<p>輸入深度 ${p.depth} m，該層重量 ${p.bw} tf。三項須配合各自地震分析工況使用，不在此合併為单一樓層載重。</p>`);$('steps').innerHTML=h;}
$('addFloor').onclick=()=>{const h=(floors.at(-1)?.h||0)+4;floors.push({h,w:500});$('height').value=h;floorUI();update();};
$('floorInputs').addEventListener('input',e=>{const i=e.target.dataset.floor;if(i===undefined)return;floors[+i][e.target.dataset.key]=e.target.value===''?NaN:+e.target.value;if(e.target.dataset.key==='h'&&+i===floors.length-1)$('height').value=e.target.value;update();});
$('floorInputs').addEventListener('click',e=>{const i=e.target.dataset.removeFloor;if(i===undefined||floors.length===1)return;floors.splice(+i,1);$('height').value=floors.at(-1).h;floorUI();update();});
$('addFault').onclick=()=>{faults.push({index:0,distance:5});faultUI();update();};
$('faultRows').addEventListener('change',e=>{const i=e.target.dataset.fault;if(i===undefined)return;faults[+i][e.target.dataset.key]=e.target.value===''?NaN:+e.target.value;if(e.target.dataset.key==='index')faultUI();update();});
$('faultRows').addEventListener('input',e=>{if(e.target.dataset.key!=='distance')return;faults[+e.target.dataset.fault].distance=e.target.value===''?NaN:+e.target.value;update();});
$('faultRows').addEventListener('click',e=>{const i=e.target.dataset.removeFault;if(i===undefined)return;faults.splice(+i,1);faultUI();update();});
$('height').addEventListener('input',()=>{const h=Number($('height').value);if(h>0&&Number.isFinite(h)){let old=floors.at(-1).h;if(old>0)floors=floors.map(f=>({...f,h:Math.round(f.h*h/old*1000)/1000}));floorUI();}});
document.querySelectorAll('aside input,aside select').forEach(el=>{if(['city','district','village'].includes(el.id))return;el.addEventListener('input',update);el.addEventListener('change',update);});
function resultTab(b){document.querySelectorAll('[data-tab]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-selected',String(x===b));x.tabIndex=x===b?0:-1;});document.querySelectorAll('.tab').forEach(s=>s.hidden=s.id!==b.dataset.tab);}
document.querySelectorAll('[data-tab]').forEach(b=>{b.id='result-tab-'+b.dataset.tab;b.setAttribute('role','tab');b.setAttribute('aria-controls',b.dataset.tab);b.setAttribute('aria-selected',String(b.classList.contains('active')));b.tabIndex=b.classList.contains('active')?0:-1;$(b.dataset.tab).setAttribute('role','tabpanel');$(b.dataset.tab).setAttribute('aria-labelledby',b.id);b.onclick=()=>resultTab(b);});
function inputTab(b){document.querySelectorAll('[data-input-tab]').forEach(x=>{let active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active));x.tabIndex=active?0:-1;$('input-'+x.dataset.inputTab).hidden=!active;});document.querySelector('.input-scroll').scrollTop=0;}
document.querySelectorAll('[data-input-tab]').forEach(b=>b.onclick=()=>inputTab(b));
document.querySelectorAll('[role=tablist]').forEach(list=>list.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const buttons=[...list.querySelectorAll('[role=tab]')],i=buttons.indexOf(document.activeElement);if(i<0)return;e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[j].click();buttons[j].focus();}));
$('editWeights').onclick=()=>{resultTab(document.querySelector('[data-tab=floors]'));$('resultPanel').scrollIntoView({behavior:'smooth',block:'start'});};
$('expandSteps').onclick=()=>{const all=[...document.querySelectorAll('#steps details')],expand=!all.every(el=>el.open);all.forEach(el=>{el.open=expand;if(expand)openSteps.add(el.dataset.step);else openSteps.delete(el.dataset.step);});$('expandSteps').textContent=expand?'收合全部':'展開全部';$('expandSteps').setAttribute('aria-expanded',String(expand));};
let printOpen=[];window.addEventListener('beforeprint',()=>{printOpen=[...document.querySelectorAll('#steps details')].map(el=>el.open);document.querySelectorAll('#steps details').forEach(el=>el.open=true);});window.addEventListener('afterprint',()=>document.querySelectorAll('#steps details').forEach((el,i)=>el.open=printOpen[i]??false));

$('chartType').onchange=renderChart;$('print').onclick=()=>{if(current)window.print();};floorUI();faultUI();modeUI();update();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_seismic_calculation',description:'讀取本頁目前地震力參數與計算結果；不代表結構安全檢核。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('不接受額外參數');if(!current)throw Error('輸入未完成');return {parameters:params,W:current.W,x:current.x,y:current.y,z:current.z,dynamicRequired:current.dynamic};}})).catch(()=>{});}catch(e){}}
