/* Reports read actual calculation records. No independent structural formulas. */
(()=>{
'use strict';
let buildingSnapshot=null,componentSnapshot=null;
const titles={mode:'工址類型',soil:'地盤類別',zone:'盆地轉換週期',fumBasis:'FuM分界依據',height:'建築高度 Hn',I:'建築用途係數 I',ay:'起始降伏地震力放大係數 αy',tx:'X分析週期',ty:'Y分析週期',tv:'垂直週期',ctx:'X經驗週期係數',cty:'Y經驗週期係數',rx:'X韌性 R',ry:'Y韌性 R',rv:'垂直韌性 Rv',depth:'地下室深度',bw:'地下層重量',irregular:'不規則',mixed:'混合系統',special:'特殊條件',sds:'SDS',ip:'設備用途係數 Ip',ap:'構材放大係數 ap',rp:'構材韌性容量 Rp',w:'設備重量 Wp',hn:'建築高度 hn',hx:'設備安裝高度 hx'};
const units={height:'m',depth:'m',hn:'m',hx:'m',tx:'s',ty:'s',tv:'s',zone:'s',bw:'tf',w:'tf'};
const inputRows=p=>Object.entries(p).filter(([k,v])=>!['floors','raw','vs30'].includes(k)&&typeof v!=='object').map(([k,v])=>({label:titles[k]||k,value:String(v),unit:units[k]||'無因次'}));
function helperStep(label,t){
 if(t.kind==='interp')return {title:label+'：實際查表／內插',formula:t.branch==='linear'?'y = y₀+(y₁−y₀)(x−x₀)/(x₁−x₀)':'表列端點夾取，不外推',substitution:t.branch==='linear'?`${t.ys[t.lo]}+(${t.ys[t.hi]}−${t.ys[t.lo]})×(${t.x}−${t.xs[t.lo]})÷(${t.xs[t.hi]}−${t.xs[t.lo]})`:`x=${t.x}，${t.branch==='lower'?'下':'上'}端表值=${t.value}`,result:t.value,condition:`實際欄序（1起算）${t.lo+1}→${t.hi+1}；x完整表列 ${t.xs.join(' | ')}；y完整表列 ${t.ys.join(' | ')}。`,source:'工址Fa/Fv：規範表2-4；斷層：DATA.faults原附件逐列資料，距離km。'};
 if(t.kind==='fu'){const expressions={initial:`1+(${t.q}−1)×${t.t}÷(0.2×${t.t0})`,sqrt:`√(2×${t.r}−1)=${t.q}`,transition:`${t.q}+(${t.r}−${t.q})×(${t.t}−0.6×${t.t0})÷(0.4×${t.t0})`,R:String(t.r)};return {title:label+'：Fu實際分段',formula:'q=√(2R−1)；依0.2T₀、0.6T₀、T₀分段',substitution:`T=${t.t}；R=${t.r}；T₀=${t.t0}；q=${t.q}\n本次式：${expressions[t.branch]}`,result:t.value,condition:`分段=${t.branch}；邊界0.2T₀=${.2*t.t0}，0.6T₀=${.6*t.t0}。`,source:'規範式2-12；FuM依本次選擇T0D或附件T0M。'};}
 if(t.kind==='spectrum')return {title:label+'：反應譜實際分段',formula:t.branch==='rising'?'Sa=S(0.4+3T/T₀)':t.branch==='plateau'?'Sa=S':'Sa=max(S₁/T, 下限)',substitution:t.branch==='rising'?`${t.s}×(0.4+3×${t.t}/${t.t0})`:t.branch==='plateau'?String(t.s):`max(${t.s1}/${t.t},${t.floor?.4*t.s:0})`,result:t.value,condition:`T=${t.t} s；T₀=${t.t0} s；分段=${t.branch}；${t.floor?'採0.4S下限':'位移用譜不採0.4S下限'}。`,source:'規範第二章工址5%阻尼反應譜。'};
 return {title:label+'：地震力修正實際分段',formula:t.branch==='identity'?'m(q)=q':t.branch==='middle'?'m(q)=0.52q+c':'m(q)=0.7q',substitution:t.branch==='identity'?String(t.q):t.branch==='middle'?`0.52×${t.q}+${t.c}`:`0.7×${t.q}`,result:t.value,condition:`q=${t.q}；第一界=${t.a}，第二界=${t.b}；垂直=${t.vertical}，近斷層=${t.near}；本次分段=${t.branch}。`,source:'規範第二章設計地震力修正式；保持原引擎邊界比較。'};
}
function buildingDiagram(p,r){const n=p.floors.length,indices=n<=6?Array.from({length:n},(_,i)=>i):[0,1,Math.floor((n-1)/2),n-3,n-2,n-1],max=Math.max(...r.dx.rows.map(f=>f.force));let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 420" role="img" aria-label="本次楼層標高與X向地震力"><rect width="360" height="420" fill="#edf4f7"/><path d="M35 375H330M45 65V375M175 65V375" stroke="#244259" stroke-width="3" fill="none"/>';
 for(const i of indices){const f=r.dx.rows[i],y=375-300*f.h/p.height,len=25+95*f.force/max;svg+=`<path d="M45 ${y}H175M175 ${y}h${len}m-7-5 7 5-7 5" stroke="#1768ac" stroke-width="2" fill="none"/><text x="48" y="${y-8}" font-size="15" fill="#244259">${i+1}F ${fmt(f.h,1)} m</text><text x="185" y="${y+17}" font-size="15" fill="#244259">${fmt(f.force,3)} tf</text>`;}
 return svg+`<text x="15" y="28" font-size="17" fill="#244259">X總橫力 ${fmt(r.x.V,3)} tf</text><text x="15" y="50" font-size="16" fill="#244259">Y總橫力 ${fmt(r.y.V,3)} tf；Hn ${p.height} m</text><text x="15" y="405" font-size="13" fill="#244259">${n>6?'抽示6層；全樓層數值見表格':'樓層力箭頭示意；完整值見表格'}</text></svg>`;
}
function componentDiagram(p,r){const y=240-150*p.hx/p.hn;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 300" role="img" aria-label="本次設備安裝高度與水平垂直力"><rect width="360" height="300" fill="#edf4f7"/><path d="M40 80V240H180V80M25 240H335" stroke="#244259" stroke-width="3" fill="none"/><rect x="100" y="${y-20}" width="35" height="20" fill="#1768ac"/><path d="M135 ${y-10}h100m-8-5 8 5-8 5M115 ${y-20}v-35m-5 8 5-8 5 8" stroke="#bc781f" stroke-width="2" fill="none"/><text x="15" y="28" font-size="17" fill="#244259">hx ${p.hx} / hn ${p.hn} m</text><text x="15" y="52" font-size="16" fill="#244259">Fph ${fmt(r.fh,4)} tf；±Fpv ${fmt(r.fv,4)} tf</text><text x="15" y="280" font-size="14" fill="#244259">高度與力向示意；不代表錨栓配置合格</text></svg>`;}
function buildBuilding(p,r){
 const inputs=inputRows(p),steps=[],tables=[];inputs.push({label:'四個區域係數（原輸入）',value:p.raw.join(' / '),unit:'無因次'},{label:'工址資料記錄',value:$('locationNote').textContent,unit:''});
 const selected=locations[Number($('village').value)],match=selected&&selected.mode===p.mode&&(p.mode==='basin'?selected.zone===p.zone:selected.raw.every((v,i)=>v===p.raw[i]));
 steps.push({title:'區域資料來源與實際輸入',result:`實際採用 raw=${p.raw.join(', ')}；地盤${p.soil}；${match?'與目前選取表列組合一致':'目前數值未確認與選取表列完全一致，依手動輸入計算'}`,condition:'行政區、村里與斷層適用性仍須確認；目前選取不等於自動地理判定。',source:'DATA.general、DATA.basin：附件與雙北113修正表；本次工址記錄見輸入。'});
 if(p.vs30?.result){const v=p.vs30.result;for(const [i,a] of v.rows.entries())steps.push({title:`Vs30 第${i+1}層實際截取`,formula:'used=max(0,min(d,30−top))；t=used/Vs',substitution:`max(0,min(${a.d},30−${a.top}))=${a.used} m；${a.used}/${a.vs}`,result:a.time,unit:'s',condition:`底深${a.bottom} m；${a.used===0?'30m以下不計入':a.used<a.d?'跨30m截取':'全層採用'}。`,source:a.source||'當次輸入分層資料，未填來源。'});steps.push({title:'Vs30及地盤分類',formula:'Vs30=30/Σ(used/Vs)',substitution:`30/${v.travel}`,result:v.value,unit:'m/s',condition:`≥270第一類；≥180第二類；其餘第三類（既有8EPS邊界容許）。本次第${v.soil}類；${p.vs30.basin?'盆地僅供參考':p.vs30.auto?'已實際帶入分類':'僅預覽，仍採手動分類'}。`,source:'規範§2.5 式2-5a，僅地表下30m，不外推。'});}
 for(const f of r.nearRows){const index=DATA.faults.findIndex(v=>v.name===f.name);tables.push({title:'近斷層原資料：'+f.name,source:`data.js → DATA.faults[${index}] → values（四列震區係數）`,headers:['係數 / 距離km','1','3','5','7','9','11','13','14'],rows:f.values.map((row,i)=>[['SSᴰ','S1ᴰ','SSᴹ','S1ᴹ'][i],...row.map(String)])});f.trace.interpolation.forEach((t,i)=>steps.push(helperStep(f.name+' '+['SSᴰ','S1ᴰ','SSᴹ','S1ᴹ'][i],t)));steps.push({title:f.name+'逐項包絡',formula:'四個raw各取max(此前值,本斷層值)',substitution:`前值=${f.trace.rawBefore.join(', ')}；本斷層=${f.computed.join(', ')}`,result:f.trace.rawAfter.join(', '),condition:'不同係數可由不同斷層控制；不中途取整。'});}
 for(const [name,site] of [['採用工址',r.site],...(p.mode==='near'?[['中小度未含近斷層',r.base]]:[])]){
  if(site.trace){tables.push({title:name+' Fa/Fv原表地盤列',source:`表2-4 地盤類別${p.soil}；Engine.amplify第${p.soil}列`,headers:['項目','欄1','欄2','欄3','欄4','欄5'],rows:[['Fa橫軸','.5','.6','.7','.8','.9'],['Fa',...site.trace.fa.map(String)],['Fv橫軸','.3','.35','.4','.45','.5'],['Fv',...site.trace.fv.map(String)]]});site.trace.interpolations.forEach((t,i)=>{steps.push(helperStep(name+' '+['Faᴰ','Fvᴰ','Faᴹ','Fvᴹ'][i],t));steps.push({title:name+'譜係數'+i,formula:'採用係數=raw×Fa/Fv',substitution:`${site.raw[i]}×${site.factors[i]}`,result:site.values[i],condition:'實際原表列／内插係數；無額外修正。'});});}
  else steps.push({title:'臺北盆地譜係數',formula:'SDS=.6；SD1=.6T₀；SMS=.8；SM1=.8T₀',substitution:`T₀=${p.zone} s`,result:site.values.join(', '),condition:'採表2-6(c)，不再套一般地盤Fa/Fv。'});
 }
 steps.push({title:'轉換週期與重量',formula:'T₀D=SD1/SDS；T₀M=SM1/SMS；W=ΣWi',substitution:`${r.s1}/${r.s}；${r.m1}/${r.m}；${p.floors.map(f=>f.w).join('+')}`,result:`T₀D=${r.t0} s；T₀M=${r.tm} s；W=${r.W} tf`});
 for(const [axis,d] of [['X',r.x],['Y',r.y],['Z',r.z]]){
  steps.push({title:axis+'週期／韌性採用',formula:axis==='Z'?'T=Tv；Ra=1+(R−1)/分母':'Tc=CtHn^0.75；T=min(T分析,1.4Tc)；Ra=1+(R−1)/分母',substitution:`Tc=${d.trace.ct}×${p.height}^0.75=${d.Tc}；上限=${d.trace.periodUpper}；T分析=${d.T}；R=${d.R}；分母=${p.mode==='basin'?2:1.5}`,result:`T=${d.t} s；Ra=${d.ra}；譜倍率k=${d.trace.k}`,condition:`FuM採${d.trace.fumBasis}；垂直週期不套水平週期上限。`});
  for(const key of ['fd','fm','fs','sd','sm','ss','md','mm','ms'])d.trace[key].forEach(t=>steps.push(helperStep(axis+' '+key,t)));
  steps.push({title:axis+'實際譜倍率與係數',formula:'SaD=k·譜D；SaM=k·譜M；Cd=I·md/(1.4αy)；Cs=I·Fs·ms/(div·αy)；Cm=I·mm/(1.4αy)',substitution:`k=${d.trace.k}；SaD=${d.sd}；SaM=${d.sm}；Sa小=${d.ss}\nCd：${p.I}×${d.md}/(1.4×${p.ay})\nCs：${p.I}×${d.fs}×${d.ms}/(${r.div}×${p.ay})\nCm：${p.I}×${d.mm}/(1.4×${p.ay})`,result:`Cd=${d.cd}；Cs=${d.cs}；Cm=${d.cm}`});
  steps.push({title:axis+'三工況包絡與力',formula:'C=max(Cd,Cs,Cm)；V=CW',substitution:`max(${d.cd},${d.cs},${d.cm})；${d.C}×${r.W}`,result:axis==='Z'?`梁板垂直係數Kz=±${d.C}`:`${d.V} tf`,condition:d.control+'；垂直載重分別乘對應靜載重，非整棟水平力替代。'});
  if(axis!=='Z'){for(const key of ['driftFu','driftSa','driftModify'])d.trace[key].forEach(t=>steps.push(helperStep(axis+'位移 '+key,t)));steps.push({title:axis+'位移用地震力',formula:'VD/W=Fu·m(Sa/Fu)/4.2；VD=(VD/W)W',substitution:`${d.trace.driftFuValue}×${d.trace.driftModify[0].value}/4.2；${d.driftC}×${r.W}`,result:d.driftV,unit:'tf',condition:'採未截斷分析週期、I=1、不採0.4S下限；實際側移仍須模型。'});}
 }
 steps.push({title:'柱牆自重垂直係數',formula:'0.4kv·SDS·I/αy',substitution:`0.4×${r.z.trace.k}×${r.s}×${p.I}/${p.ay}`,result:r.columnC,condition:'正負方向各乘柱牆對應自重。'});
 if(r.basement){const b=r.basement;steps.push({title:'地下室三工況',formula:'depth=max(1−H/40,.5)；kb=.1depth·I；KD=kb·SDS；K*=KD/div；KM=kb·SMS',substitution:`max(1−${p.depth}/40,.5)=${b.depthFactor}；kb=${b.kb}；KD=${b.kd}；K*=${b.ks}；KM=${b.km}；各乘Wb=${p.bw}`,result:`設計=${b.design}；中小=${b.small}；最大=${b.maximum} tf`,condition:'三工況分別使用；深度因子下限0.5，不合併。',source:'規範§2.12；已將原畫面相同算式移入實際引擎。'});}
 for(const [axis,d,dist] of [['X',r.x,r.dx],['Y',r.y,r.dy]]){
  steps.push({title:axis+'頂層力與分配分母',formula:'T≤.7：Ft=0；否則Ft=min(.07T,.25)V；ΣWi hi',substitution:`T=${d.t}；Ft係數=${dist.trace.ftCoefficient}；V=${d.V}；ΣWh=${dist.trace.denominator}`,result:dist.ft,unit:'tf',condition:'Ft上限0.25V；保留原條件與未取整值。'});
  dist.rows.forEach((f,i)=>steps.push({title:`${axis} ${i+1}F實際力／累積剪力`,formula:'Fi=(V−Ft)Wi hi/ΣWh+屋頂Ft；Qi=Σ上方Fi',substitution:`(${d.V}−${dist.ft})×${f.w}×${f.h}/${dist.trace.denominator}+${f.trace.roofExtra}\n實際分子=${f.trace.numerator}；基本分配=${f.trace.baseForce}\nQi=${dist.rows.slice(i).map(v=>v.force).join('+')}`,result:`Fi=${f.force} tf；Qi=${f.shear} tf`}));
  steps.push({title:axis+'力平衡與基面力矩',formula:'ΣFi；M=ΣFi hi',substitution:dist.rows.map(f=>`${f.force}×${f.h}`).join('+'),result:`ΣFi=${dist.sumForce} tf；ΣFi−V=${dist.sumForce-d.V} tf；M=${dist.moment} tf·m`,condition:'未施加基面力矩折減。'});
 }
 tables.push({title:'完整樓層输入與同次力／剪力',source:'當次楼層重量與Engine.distribute結果',headers:['樓層','h m','W tf','Fx tf','Fy tf','Qx tf','Qy tf'],rows:p.floors.map((f,i)=>[String(i+1),String(f.h),String(f.w),String(r.dx.rows[i].force),String(r.dy.rows[i].force),String(r.dx.rows[i].shear),String(r.dy.rows[i].shear)])});
 steps.push({title:'顯示取整與分析門檻',result:'所有引擎中間值／結果使用Number完整精度；未四捨五入。畫面fmt小數顯示不回寫計算。',condition:`Hn=${p.height} m，樓層=${p.floors.length}，特殊=${p.special}，不規則=${p.irregular}，混合=${p.mixed}；dynamic=${r.dynamic}。依原門檻判定，不等於整棟安全。`});
 return {title:'地震力分析詳細計算報告',summary:$('locationNote').textContent,inputs,steps,tables,conclusions:[`X V=${r.x.V} tf；Y V=${r.y.V} tf；梁板Kz=±${r.z.C}；柱牆係數=±${r.columnC}。`,r.dynamic?'須另作動力／專案分析；本頁為靜力基準。':'靜力法初步篩選仍須確認完整適用條件。','地震力需求與計算紀錄，不宣稱結構／法規合格。'],diagram:{svg:buildingDiagram(p,r),width:360,height:420,caption:'同次樓層標高與X向力；超過六層時抽示六層，所有樓層完整值見表。'}};
}
function buildComponent(run){const {p,r}=run,steps=[{title:'設備／構材係數來源',result:run.type,source:run.group==='custom'?'使用者自訂依據（輸入列出）':`ComponentEngine.types[${run.typeIndex}]；規範表${run.group}；欄3 ap=${p.ap}、欄4 Rp=${p.rp}`},{title:'用途係數與Rpa',formula:'Ip=max(設備Ip,建築I)；Rpa=1+(Rp−1)/分母',substitution:`max(${p.ip},${p.I})；1+(${p.rp}−1)/${r.trace.rpaDivisor}`,result:`Ip=${r.ip}；Rpa=${r.rpa}`},{title:'安裝高度放大',formula:'1+2hx/hn',substitution:`1+2×${p.hx}/${p.hn}`,result:r.height,condition:'0≤hx≤hn；不外推安裝高度。'},{title:'水平力基本式',formula:'Fph,raw=.4SDS·Ip·ap/Rpa·高度放大·Wp',substitution:`.4×${p.sds}×${r.ip}×${p.ap}/${r.rpa}×${r.height}×${p.w}`,result:r.raw,unit:'tf'},{title:'上下限及採用',formula:'min(1.6SDS·Ip·Wp,max(.3SDS·Ip·Wp,raw))',substitution:`下限=.3×${p.sds}×${r.ip}×${p.w}=${r.min}；上限=1.6×${p.sds}×${r.ip}×${p.w}=${r.max}\nmin(${r.max},max(${r.min},${r.raw}))`,result:r.fh,unit:'tf',condition:r.control},{title:'垂直力與無因次係數',formula:'Fpv=kvFph；Ch=Fph/Wp；Cv=Fpv/Wp',substitution:`${r.ratio}×${r.fh}；${r.fh}/${p.w}；${r.fv}/${p.w}`,result:`Fpv=±${r.fv} tf；Ch=${r.coefficient}；Cv=±${r.fv/p.w}`},{title:'tf／kN單位換算',formula:'1tf=9.80665kN',substitution:`Fph ${r.fh}×9.80665；Fpv ${r.fv}×9.80665`,result:`水平${r.fh*9.80665} kN；垂直±${r.fv*9.80665} kN`},...Object.entries(run.capacities).map(([id,c])=>({title:id==='cpCapH'?'水平承載力比較':'垂直承載力比較',formula:c.provided?'需求／承載力':'未提供，不作比較',substitution:c.provided?`${c.demand}/${c.capacity}`:'',result:c.provided?c.ratio:'未檢核',condition:c.provided?(c.ok?'需求≤輸入承載力':'需求>輸入承載力'):'不將未輸入承載力當作合格。'})),{title:'取整與適用邊界',result:'未在計算過程取整；画面小數顯示不影響判定。',condition:'Rp≥1；所有必填正數及0≤hx≤hn檢核通過；比較未包括其他載重組合、錨栓或相對位移。'}];
 return {title:'附屬構體與設備地震力詳細報告',summary:run.type,inputs:inputRows(p),steps,conclusions:[`水平需求${r.fh} tf；垂直需求±${r.fv} tf。`,'需求／承載力比較僅針對本次分量，不代表完整構材、錨定或耐震合格。'],diagram:{svg:componentDiagram(p,r),width:360,height:300,caption:'同次安裝高度與力向，不表示施工錨栓配置。'}};}
const mainButton=document.createElement('button');mainButton.id='exportBuildingDocx';mainButton.textContent='匯出詳細Word';$('print').after(mainButton);
const panel=document.createElement('details');panel.className='step';panel.id='actual-engine-trace';$('steps').after(panel);
function renderReportPanel(node,report){node.innerHTML='<summary>同次引擎完整紀錄（含原表／Word）</summary><div class="step-content">'+report.steps.map((s,i)=>`<h3>${i+1}. ${esc(s.title)}</h3>`+['formula','substitution','result','condition','source'].filter(k=>s[k]!=null&&s[k]!=='').map(k=>`<p class="formula" style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(s[k])}${k==='result'&&s.unit?' '+esc(s.unit):''}</p>`).join('')).join('')+'<div style="max-width:400px">'+report.diagram.svg+'</div></div>';}
function captureBuilding(){buildingSnapshot=current&&params?JSON.parse(JSON.stringify(buildBuilding(params,current))):null;mainButton.disabled=!buildingSnapshot;panel.hidden=!buildingSnapshot;if(buildingSnapshot)renderReportPanel(panel,buildingSnapshot);else panel.innerHTML='';}
function captureComponent(){const node=$('cpResults');node.querySelector('#component-engine-trace')?.remove();componentSnapshot=globalThis.SeismicComponentRun?JSON.parse(JSON.stringify(buildComponent(globalThis.SeismicComponentRun))):null;if(!componentSnapshot)return;const el=document.createElement('details');el.id='component-engine-trace';el.className='step';renderReportPanel(el,componentSnapshot);const b=document.createElement('button');b.id='exportComponentDocx';b.textContent='匯出設備詳細Word';b.onclick=async()=>{try{update();if(!componentSnapshot)throw Error('設備輸入無效，不能匯出。');const snap=JSON.parse(JSON.stringify(componentSnapshot));await CalculationDocx.download(snap,'設備地震力_詳細計算.docx');}catch(e){alert(e.message)}};el.append(b);node.append(el);}
mainButton.onclick=async()=>{try{update();if(!buildingSnapshot)throw Error('主建築輸入無效，不能匯出。');const snap=JSON.parse(JSON.stringify(buildingSnapshot));await CalculationDocx.download(snap,'地震力分析_詳細計算.docx');}catch(e){alert(e.message)}};
document.addEventListener('seismic-updated',captureBuilding);document.addEventListener('component-updated',captureComponent);captureBuilding();captureComponent();
})();
